### ISSUE TITLE
Sharing iP code quality feedback [for @arnav-goel10]

### ISSUE THREAD

**Issue by soc-se-bot-red** [arnav-goel10/ip#1]
@arnav-goel10 We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

No easy-to-detect issues :+1: 

### Aspect: Recent Git Commit Message

possible problems in commit [`62b6378`](https://github.com/arnav-goel10/ip/commit/62b6378c3a19e87880f7727981b2e69a598123e2):

```

Fix


```

* Perhaps too short (?)
             

**Suggestion:** Follow the given [conventions for Git commit messages](https://se-education.org/guides/conventions/git.html) for _future_ commits (do not modify past commit messages as doing so will change the commit timestamp that we used to detect your commit timings).

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by arnav-goel10** [comment]
Fixed!
