### ISSUE TITLE
Sharing iP code quality feedback [for @arnav-goel10] - Round 2

### ISSUE THREAD

**Issue by soc-se-bot-red** [arnav-goel10/ip#3]
@arnav-goel10 We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, so that you can avoid similar problems in your tP code (which will be graded more strictly for code quality).

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/darkpool/parser/validator/ValidateDeadline.java` lines `13-17`](https://github.com/arnav-goel10/ip/blob/77c6751717ce2d6421aa56c9ae4d67552f8ab022/src/main/java/darkpool/parser/validator/ValidateDeadline.java#L13..L17):

```java

    /**
     * validate method checks if the deadline command is valid.
     * @param userInput The user input command.
     * @throws DarkpoolException If the deadline command is invalid.
     */

```

Example from [`src/main/java/darkpool/parser/validator/ValidateDeadline.java` lines `24-28`](https://github.com/arnav-goel10/ip/blob/77c6751717ce2d6421aa56c9ae4d67552f8ab022/src/main/java/darkpool/parser/validator/ValidateDeadline.java#L24..L28):

```java

    /**
     * validateBy method checks if the deadline command contains the keyword "/by".
     * @param text The user input command.
     * @throws DarkpoolException If the deadline command does not contain the keyword "/by".
     */

```

Example from [`src/main/java/darkpool/parser/validator/ValidateDeadline.java` lines `35-39`](https://github.com/arnav-goel10/ip/blob/77c6751717ce2d6421aa56c9ae4d67552f8ab022/src/main/java/darkpool/parser/validator/ValidateDeadline.java#L35..L39):

```java

    /**
     * validateEmptyDesc method checks if the deadline description is empty.
     * @param desc The deadline description.
     * @throws DarkpoolException If the deadline description is empty.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:exclamation: You are not _required_ to (but you are welcome to) fix the above problems in your iP, unless you have been separately asked to resubmit the iP due to code quality issues.

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by arnav-goel10** [comment]
Updated header comments
